"""empty message

Revision ID: 2bdd2b16286f
Revises: 
Create Date: 2021-04-06 23:17:37.407941

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2bdd2b16286f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('sender', table_name='message')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('sender', 'message', ['sender'], unique=True)
    # ### end Alembic commands ###
