"""empty message

Revision ID: 637fd7d54ea2
Revises: 
Create Date: 2021-04-19 23:44:16.645463

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '637fd7d54ea2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('room',
    sa.Column('room_id', sa.Integer(), nullable=False),
    sa.Column('room_key', sa.String(length=50), nullable=False),
    sa.Column('members', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('room_id'),
    sa.UniqueConstraint('room_key')
    )
    op.create_table('message',
    sa.Column('message_id', sa.Integer(), nullable=False),
    sa.Column('sender', sa.String(length=40), nullable=False),
    sa.Column('message_content', sa.Text(), nullable=False),
    sa.Column('time_stamp', sa.DateTime(), nullable=False),
    sa.Column('room_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['room_id'], ['room.room_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('message_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('message')
    op.drop_table('room')
    # ### end Alembic commands ###
